In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4])
print(a1)

[1 2 3 4]


In [3]:
type(a1)

numpy.ndarray

In [4]:
a1.ndim

1

In [5]:
a2=np.array([[1,2,3,4],[2,3,4,5]])

In [6]:
a2.ndim

2

In [7]:
a2.size

8

In [8]:
a1.size

4

In [9]:
a2.shape

(2, 4)

In [10]:
a3=np.array([[1,2,3],[2,3,4],[4,5,6]])

In [11]:
print(a3)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [12]:
a3.shape

(3, 3)

In [13]:
a3.ndim

2

In [14]:
a3.size

9

In [15]:
a3.dtype

dtype('int32')

In [16]:
np.ones(([5,5]))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.empty((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
np.empty((3,4),dtype=float)

array([[1.44830597e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.61322099e-307, 2.58093088e-057, 1.22150183e+165,
        1.20054245e-071],
       [7.79860379e-043, 1.33621993e+165, 3.34412347e-061,
        1.46388138e-075]])

In [21]:
np.arange(4,89,10)

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84])

In [22]:
np.linspace(1,100,10,dtype=int)

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [23]:
array1=np.arange(1,21).reshape(5,4)
array2=np.arange(1,21).reshape(5,4)
print(array1)
print(array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [24]:
array1+array2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [25]:
np.add(array1,array2)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40]])

In [26]:
array1*array2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256],
       [289, 324, 361, 400]])

In [27]:
array1/array2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
array1-array2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
array3=np.arange(1,10).reshape(3,3)
array4=np.arange(1,10).reshape(3,3)
print(array3)
print(array4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
array3 @ array4

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [31]:
array5=array3.dot(array4)
print(array5)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [32]:
array5.max()

150

In [33]:
array5.argmax()

8

In [34]:
array5.max(axis=0)

array([102, 126, 150])

In [35]:
array5.max(axis=1)

array([ 42,  96, 150])

In [41]:
array6= np.arange(100).reshape((10,10))
print(array6)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [46]:
array6[:, 3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [51]:
array6[2:4,4:6]

array([[24, 25],
       [34, 35]])

In [58]:
array6[]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [64]:
array6[5:7,6:8]

array([[56, 57],
       [66, 67]])

In [65]:
array6[5:7,6:8]

array([[56, 57],
       [66, 67]])

In [66]:
np.arange(100).reshape((10,10))
print(array6)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [89]:
array6[1:,6:7].reshape((3,3))

array([[16, 26, 36],
       [46, 56, 66],
       [76, 86, 96]])

In [75]:
array6[4:6,2:4]

array([[42, 43],
       [52, 53]])

In [79]:
array6[5:6,9:10]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])